version: '3.8'
services:
  frontend:
    image: vijayvenkatj/campusconnect-frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - mynetwork
    
  backend:
    image: vijayvenkatj/campusconnect-backend:latest
    restart: always
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

